# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bloggus Doekmanni
author: Doeke Zanstra
logo: /images/doekman-square.png
email: doeke@zanstra.net
description: > #
  This is Bloggus Doekmanni, or Doekman's blog if you like. A bit of drivel
  about computer programming; some dead serious, some not so much...
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.zanstra.com" # the base hostname & protocol for your site
twitter_username: doekezanstra
github_username:  doekman
keybase_username: doekman

exclude:
  - publi.sh
  - new-post.sh

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_listed: true # set `is_listed: false` to exclude it from json/xml feeds
      lang: en

collections:
  like:
    output: true
